/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteSolutionsRouteImport } from './routes/website-solutions'
import { Route as UxDesignRouteImport } from './routes/ux-design'
import { Route as TestRouteImport } from './routes/test'
import { Route as TChar38sRouteImport } from './routes/t&s'
import { Route as SuccessPageRouteImport } from './routes/success-page'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsDetailsRouteImport } from './routes/payments-details'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as MobileAppsRouteImport } from './routes/mobile-apps'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DigitalportfolioRouteImport } from './routes/digitalportfolio'
import { Route as DGVycmFjb2RlCgRouteImport } from './routes/dGVycmFjb2RlCg'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyPortfolioRouteImport } from './routes/company-portfolio'
import { Route as CloudSolutionsRouteImport } from './routes/cloud-solutions'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CancelPageRouteImport } from './routes/cancel-page'
import { Route as BusinessSoftwaresRouteImport } from './routes/business-softwares'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const WebsiteSolutionsRoute = WebsiteSolutionsRouteImport.update({
  id: '/website-solutions',
  path: '/website-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const UxDesignRoute = UxDesignRouteImport.update({
  id: '/ux-design',
  path: '/ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TChar38sRoute = TChar38sRouteImport.update({
  id: '/t&s',
  path: '/t&s',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessPageRoute = SuccessPageRouteImport.update({
  id: '/success-page',
  path: '/success-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsDetailsRoute = PaymentsDetailsRouteImport.update({
  id: '/payments-details',
  path: '/payments-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppsRoute = MobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalportfolioRoute = DigitalportfolioRouteImport.update({
  id: '/digitalportfolio',
  path: '/digitalportfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DGVycmFjb2RlCgRoute = DGVycmFjb2RlCgRouteImport.update({
  id: '/dGVycmFjb2RlCg',
  path: '/dGVycmFjb2RlCg',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPortfolioRoute = CompanyPortfolioRouteImport.update({
  id: '/company-portfolio',
  path: '/company-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudSolutionsRoute = CloudSolutionsRouteImport.update({
  id: '/cloud-solutions',
  path: '/cloud-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelPageRoute = CancelPageRouteImport.update({
  id: '/cancel-page',
  path: '/cancel-page',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSoftwaresRoute = BusinessSoftwaresRouteImport.update({
  id: '/business-softwares',
  path: '/business-softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/business-softwares': typeof BusinessSoftwaresRoute
  '/cancel-page': typeof CancelPageRoute
  '/career': typeof CareerRoute
  '/cloud-solutions': typeof CloudSolutionsRoute
  '/company-portfolio': typeof CompanyPortfolioRoute
  '/contact': typeof ContactRoute
  '/dGVycmFjb2RlCg': typeof DGVycmFjb2RlCgRoute
  '/digitalportfolio': typeof DigitalportfolioRoute
  '/home': typeof HomeRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/partnerships': typeof PartnershipsRoute
  '/payments': typeof PaymentsRoute
  '/payments-details': typeof PaymentsDetailsRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/success-page': typeof SuccessPageRoute
  '/t&s': typeof TChar38sRoute
  '/test': typeof TestRoute
  '/ux-design': typeof UxDesignRoute
  '/website-solutions': typeof WebsiteSolutionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/business-softwares': typeof BusinessSoftwaresRoute
  '/cancel-page': typeof CancelPageRoute
  '/career': typeof CareerRoute
  '/cloud-solutions': typeof CloudSolutionsRoute
  '/company-portfolio': typeof CompanyPortfolioRoute
  '/contact': typeof ContactRoute
  '/dGVycmFjb2RlCg': typeof DGVycmFjb2RlCgRoute
  '/digitalportfolio': typeof DigitalportfolioRoute
  '/home': typeof HomeRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/partnerships': typeof PartnershipsRoute
  '/payments': typeof PaymentsRoute
  '/payments-details': typeof PaymentsDetailsRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/success-page': typeof SuccessPageRoute
  '/t&s': typeof TChar38sRoute
  '/test': typeof TestRoute
  '/ux-design': typeof UxDesignRoute
  '/website-solutions': typeof WebsiteSolutionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/business-softwares': typeof BusinessSoftwaresRoute
  '/cancel-page': typeof CancelPageRoute
  '/career': typeof CareerRoute
  '/cloud-solutions': typeof CloudSolutionsRoute
  '/company-portfolio': typeof CompanyPortfolioRoute
  '/contact': typeof ContactRoute
  '/dGVycmFjb2RlCg': typeof DGVycmFjb2RlCgRoute
  '/digitalportfolio': typeof DigitalportfolioRoute
  '/home': typeof HomeRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/partnerships': typeof PartnershipsRoute
  '/payments': typeof PaymentsRoute
  '/payments-details': typeof PaymentsDetailsRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/success-page': typeof SuccessPageRoute
  '/t&s': typeof TChar38sRoute
  '/test': typeof TestRoute
  '/ux-design': typeof UxDesignRoute
  '/website-solutions': typeof WebsiteSolutionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/articles'
    | '/business-softwares'
    | '/cancel-page'
    | '/career'
    | '/cloud-solutions'
    | '/company-portfolio'
    | '/contact'
    | '/dGVycmFjb2RlCg'
    | '/digitalportfolio'
    | '/home'
    | '/mobile-apps'
    | '/partnerships'
    | '/payments'
    | '/payments-details'
    | '/pricing'
    | '/service'
    | '/success-page'
    | '/t&s'
    | '/test'
    | '/ux-design'
    | '/website-solutions'
    | '/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/articles'
    | '/business-softwares'
    | '/cancel-page'
    | '/career'
    | '/cloud-solutions'
    | '/company-portfolio'
    | '/contact'
    | '/dGVycmFjb2RlCg'
    | '/digitalportfolio'
    | '/home'
    | '/mobile-apps'
    | '/partnerships'
    | '/payments'
    | '/payments-details'
    | '/pricing'
    | '/service'
    | '/success-page'
    | '/t&s'
    | '/test'
    | '/ux-design'
    | '/website-solutions'
    | '/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/articles'
    | '/business-softwares'
    | '/cancel-page'
    | '/career'
    | '/cloud-solutions'
    | '/company-portfolio'
    | '/contact'
    | '/dGVycmFjb2RlCg'
    | '/digitalportfolio'
    | '/home'
    | '/mobile-apps'
    | '/partnerships'
    | '/payments'
    | '/payments-details'
    | '/pricing'
    | '/service'
    | '/success-page'
    | '/t&s'
    | '/test'
    | '/ux-design'
    | '/website-solutions'
    | '/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  BusinessSoftwaresRoute: typeof BusinessSoftwaresRoute
  CancelPageRoute: typeof CancelPageRoute
  CareerRoute: typeof CareerRoute
  CloudSolutionsRoute: typeof CloudSolutionsRoute
  CompanyPortfolioRoute: typeof CompanyPortfolioRoute
  ContactRoute: typeof ContactRoute
  DGVycmFjb2RlCgRoute: typeof DGVycmFjb2RlCgRoute
  DigitalportfolioRoute: typeof DigitalportfolioRoute
  HomeRoute: typeof HomeRoute
  MobileAppsRoute: typeof MobileAppsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PaymentsRoute: typeof PaymentsRoute
  PaymentsDetailsRoute: typeof PaymentsDetailsRoute
  PricingRoute: typeof PricingRoute
  ServiceRoute: typeof ServiceRoute
  SuccessPageRoute: typeof SuccessPageRoute
  TChar38sRoute: typeof TChar38sRoute
  TestRoute: typeof TestRoute
  UxDesignRoute: typeof UxDesignRoute
  WebsiteSolutionsRoute: typeof WebsiteSolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-solutions': {
      id: '/website-solutions'
      path: '/website-solutions'
      fullPath: '/website-solutions'
      preLoaderRoute: typeof WebsiteSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ux-design': {
      id: '/ux-design'
      path: '/ux-design'
      fullPath: '/ux-design'
      preLoaderRoute: typeof UxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t&s': {
      id: '/t&s'
      path: '/t&s'
      fullPath: '/t&s'
      preLoaderRoute: typeof TChar38sRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-page': {
      id: '/success-page'
      path: '/success-page'
      fullPath: '/success-page'
      preLoaderRoute: typeof SuccessPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments-details': {
      id: '/payments-details'
      path: '/payments-details'
      fullPath: '/payments-details'
      preLoaderRoute: typeof PaymentsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-apps': {
      id: '/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/mobile-apps'
      preLoaderRoute: typeof MobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalportfolio': {
      id: '/digitalportfolio'
      path: '/digitalportfolio'
      fullPath: '/digitalportfolio'
      preLoaderRoute: typeof DigitalportfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dGVycmFjb2RlCg': {
      id: '/dGVycmFjb2RlCg'
      path: '/dGVycmFjb2RlCg'
      fullPath: '/dGVycmFjb2RlCg'
      preLoaderRoute: typeof DGVycmFjb2RlCgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-portfolio': {
      id: '/company-portfolio'
      path: '/company-portfolio'
      fullPath: '/company-portfolio'
      preLoaderRoute: typeof CompanyPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-solutions': {
      id: '/cloud-solutions'
      path: '/cloud-solutions'
      fullPath: '/cloud-solutions'
      preLoaderRoute: typeof CloudSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-page': {
      id: '/cancel-page'
      path: '/cancel-page'
      fullPath: '/cancel-page'
      preLoaderRoute: typeof CancelPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-softwares': {
      id: '/business-softwares'
      path: '/business-softwares'
      fullPath: '/business-softwares'
      preLoaderRoute: typeof BusinessSoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  BusinessSoftwaresRoute: BusinessSoftwaresRoute,
  CancelPageRoute: CancelPageRoute,
  CareerRoute: CareerRoute,
  CloudSolutionsRoute: CloudSolutionsRoute,
  CompanyPortfolioRoute: CompanyPortfolioRoute,
  ContactRoute: ContactRoute,
  DGVycmFjb2RlCgRoute: DGVycmFjb2RlCgRoute,
  DigitalportfolioRoute: DigitalportfolioRoute,
  HomeRoute: HomeRoute,
  MobileAppsRoute: MobileAppsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PaymentsRoute: PaymentsRoute,
  PaymentsDetailsRoute: PaymentsDetailsRoute,
  PricingRoute: PricingRoute,
  ServiceRoute: ServiceRoute,
  SuccessPageRoute: SuccessPageRoute,
  TChar38sRoute: TChar38sRoute,
  TestRoute: TestRoute,
  UxDesignRoute: UxDesignRoute,
  WebsiteSolutionsRoute: WebsiteSolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
